trigger:
  branches:
    include:
      - main

pool:
  name: 'quizpaul'  

steps:
  - script: |
      dotnet restore
      dotnet build --configuration Release
    displayName: 'Restore and Build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*Tests/*.csproj'
    displayName: 'Run Tests'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      arguments: '-c Release -o $(Build.ArtifactStagingDirectory)'
      publishWebProjects: true
      zipAfterPublish: true
      modifyOutputPath: false
      workingDirectory: '$(Build.SourcesDirectory)/YourWebAppFolder'
    displayName: 'Publish Web Application'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'drop'
      publishLocation: 'pipeline'
    displayName: 'Publish Artifact'

